import re
import time
from pathlib import Path

from constants.companyIdMap import companyIdMap as existingMap
from utils.session import make_session, extract_companyid

BASE = "https://www.sharesansar.com"
UNIVERSE_URL = f"{BASE}/today-share-price"
MAP_PATH = Path("constants/companyIdMap.py")
DELAY = 0.3

_LINK_RE = re.compile(r"/company/([a-z0-9]+)")


def parse_universe(html):
    return {m.upper() for m in _LINK_RE.findall(html)}


def merge_maps(existing, discovered):
    merged = dict(existing)
    for sym, cid in discovered.items():
        if sym in merged and merged[sym] != cid:
            print(f"  WARNING {sym}: existing id {merged[sym]} -> {cid}")
        merged[sym] = cid
    return merged


def render_id_map(mapping):
    lines = [
        "# AUTO-GENERATED by discoverCompanies.py - do not edit by hand.",
        "# Maps NEPSE symbol -> sharesansar internal company id.",
        "companyIdMap = {",
    ]
    for sym in sorted(mapping):
        lines.append(f'    "{sym}": {mapping[sym]},')
    lines.append("}")
    return "\n".join(lines) + "\n"


def discover(session, symbols):
    discovered = {}
    for sym in sorted(symbols):
        time.sleep(DELAY)
        try:
            resp = session.get(f"{BASE}/company/{sym.lower()}")
            resp.raise_for_status()
            cid = extract_companyid(resp.text)
            if cid is None:
                print(f"  no companyid for {sym}, skipping")
                continue
            discovered[sym] = int(cid)
        except Exception as exc:  # noqa: BLE001
            print(f"  FAILED {sym}: {exc}")
    return discovered


def main():
    session = make_session()
    print("Fetching universe...")
    html = session.get(UNIVERSE_URL).text
    symbols = parse_universe(html)
    print(f"  {len(symbols)} symbols in live universe")

    discovered = discover(session, symbols)
    merged = merge_maps(existingMap, discovered)
    MAP_PATH.write_text(render_id_map(merged))
    print(f"\nWrote {len(merged)} entries to {MAP_PATH} "
          f"(was {len(existingMap)}, discovered {len(discovered)})")


if __name__ == "__main__":
    main()
